### PR TITLE
feat: tag links

### PR DESCRIPTION
**Pull request by SkyeYoung**
Changes:
Allow clicking on chip to jump to the corresponding GitHub repository

### CODE REVIEW

**Comment by SkyeYoung** [comment]
cc @guoqqqi

**Comment by guoqqqi** [comment]
Add hover to tag `cursor: pointer`

**Comment by SkyeYoung** [comment]
> Add hover to tag `cursor: pointer` is better.

resolved

**Comment by guoqqqi** [comment]
Hi, @SkyeYoung  It does not seem to be in effect

**Comment by guoqqqi** [comment]
image
Also I found a problem, when clicking the delete button, they still open a new page

**Review by guoqqqi — APPROVED** [review]
LGTM

**Pull request merged**
