### PR TITLE
feat: add mobile adaptation

### PR DESCRIPTION
**Pull request by LiteSun**
Browser:
image

Mobile:
image

### CODE REVIEW

**Comment by Yiyiyimu** [comment]
It seems the browser version is narrower than before. Is it expected?

**Comment by Yiyiyimu** [comment]
The time axis on mobile view is still not handled properly
image

BTW, I think the graph scale ratio on mobile should be like browser that length should larger than height to make it look better

**Comment by LiteSun** [comment]
> It seems the browser version is narrower than before. Is it expected?

The previous width was 70% of the browser width, and this was found to be out of proportion on widescreen monitors.
image
so I referred to Google Finance to make the width narrower

**Comment by LiteSun** [comment]
> The time axis on mobile view is still not handled properly

will fix it soon.

> I think the graph scale ratio on mobile should be like browser that length should larger than height to make it look better

In the local try to change the ratio of the length and width, I feel that the first picture is a little more coordinated
image
image

**Comment by Yiyiyimu** [comment]
> In the local try to change the ratio of the length and width, I feel that the first picture is a little more coordinated

Still take google finance as an example, I still believe length > width would be better. I think the reason the current view does not look good is due to different font sizes unmatched.

image

**Review by Yiyiyimu — APPROVED** [review]
LGTM

**Pull request merged**
